config/routes.rb
SuperCRM::Application.routes.draw do

  match 'login' => 'user_sessions#create'
  match 'logout' => 'user_sessions#destroy'
  resource :user_session
  resource :account, :controller => "users"

  root :to => 'user_sessions#create'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :password, :password_confirmation, :email

  acts_as_authentic

  def activate!
    self.activated_at = Time.now
    self.active = true
    save
  end

  def deliver_activation_instructions!
    #reset_perishable_token!
    #UserMailer.activation_instructions(self).deliver
  end

  def deliver_welcome!
    #reset_perishable_token!
    #UserMailer.welcome_email(self).deliver
  end

  def deliver_password_reset_instructions!
    #reset_perishable_token!
    #UserMailer.password_reset_instructions(self).deliver
  end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  # specify configuration here, such as:
  # logout_on_timeout true
  # ...many more options in the documentation
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  #filter_parameter_logging :password, :password_confirmation
  helper_method :current_user_session, :current_user
  
  private
  def current_user_session
    return @current_user_session if defined?(@current_user_session)
    @current_user_session = UserSession.find
  end
  
  def current_user
    return @current_user if defined?(@current_user)
    @current_user = current_user_session && current_user_session.user
  end
  
  def current_admin
    if current_user
      if current_user.username == 'admin'
        result = true
      else
        result = false
      end
    else
      result = false
    end
    result
  end
  
  def require_user
    unless current_user
      store_location
      flash[:notice] = "You must be logged in to access this page"
      redirect_to new_user_session_url
      return false
    end
  end
  
  def require_admin 
    if current_user
      if current_user.username == 'admin'
        return true          
      end
    end
    store_location
    flash[:notice] = "You must be logged out to access this page"
    redirect_to account_url
    return false
  end
  
  def require_no_user
    if current_user
      store_location
      flash[:notice] = "You must be logged out to access this page"
      redirect_to account_url
      return false
    end
  end
  
  def store_location
    session[:return_to] = request.url
  end
  
  def redirect_back_or_default(default)
    redirect_to(session[:return_to] || default)
    session[:return_to] = nil
  end  
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      redirect_to account_url
    else
      render :action => :new
    end
  end

  def destroy
    current_user_session.destroy
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => [:show, :edit, :update]
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])

    # Saving without session maintenance to skip
    # auto-login which can't happen here because
    # the User has not yet been activated
    if @user.save_without_session_maintenance
      @user.deliver_activation_instructions!
      flash[:notice] = "Your account has been created. Please check your e-mail for your account activation instructions!"
      redirect_to root_url
    else
      render :action => :new
    end
  end
  
  def show
    @user = @current_user
  end

  def edit
    @user = @current_user
  end
  
  def update
    @user = @current_user # makes our views "cleaner" and more consistent
    if @user.update_attributes(params[:user])
      flash[:notice] = "Account updated!"
      redirect_to account_url
    else
      render :action => :edit
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_left_side.html.haml
.left-nav.clearfix
  .left-primary-nav
    %ul#myTab
      %li.active
        %a.icon-desktop{"data-original-title" => "Dashboard", :href => "#main"}
      %li
        %a.icon-th-large{"data-original-title" => "Forms", :href => "#forms"}
      %li
        %a.icon-beaker{"data-original-title" => "Features", :href => "#features"}
      %li
        %a.icon-list-alt{"data-original-title" => "UI Elements", :href => "#ui-elements"}
      %li
        %a.icon-file-alt{"data-original-title" => "Pages", :href => "#pages"}
      %li
        %a.icon-bar-chart{"data-original-title" => "Chart", :href => "#chart"}
    %ul
      %li
        %a.icon-comments{"data-original-title" => "Chat", :href => "chat.html"}
      %li
        %a.icon-pencil{"data-original-title" => "WYSIWYG editor", :href => "text-editor.html"}
  .responsive-leftbar
    %i.icon-list
  .left-secondary-nav.tab-content
    #main.tab-pane.active
      %h4.side-head Dashboard
      .search-box
        .input-append.input-icon
          %input.search-input{:placeholder => "Search...", :type => "text"}/
          %i.icon-search
          %button.btn{:type => "button"} Go!
      %ul.metro-sidenav.clearfix
        %li
          %span.notify-tip 30
          %a.brown{:href => "#"}
            %i.icon-user
            %span User
        %li
          %a.orange{:href => "#"}
            %i.icon-cogs
            %span Settings
        %li
          %a.blue-violate{:href => "#"}
            %i.icon-lightbulb
            %span Support
        %li
          %a.magenta{:href => "#"}
            %i.icon-bar-chart
            %span Statistics
        %li
          %a.green{:href => "#"}
            %i.icon-shopping-cart
            %span Orders
        %li
          %a.bondi-blue{:href => "#"}
            %i.icon-time
            %span Events
        %li
          %a.dark-yellow{:href => "#"}
            %i.icon-file-alt
            %span Post
        %li
          %a.blue{:href => "#"}
            %i.icon-copy
            %span Documents
      .side-widget
        .board-widgets.light-blue
          .board-widgets-head.clearfix
            %h4.pull-left Bandwidth Usage
            %a.widget-settings{:href => "#"}
              %i.icon-cloud
          .board-widgets-content
            .progress.progress-striped.active.min.progress-info
              .bar{:style => "width: 48%;"}
            .stat-text.progress-stat
              %i.progres-percent 48%
              12000 MB / 25000 MB
        .board-widgets.light-blue
          .board-widgets-head.clearfix
            %h4.pull-left Disk Usage
            %a.widget-settings{:href => "#"}
              %i.icon-hdd
          .board-widgets-content
            .progress.progress-striped.active.min.progress-success
              .bar{:style => "width: 20%;"}
            .stat-text.progress-stat
              %i.progres-percent 20%
              50GB / 250 GB
        .board-widgets.gray
          .board-widgets-head.clearfix
            %h4.pull-left Visitors
            %a.widget-settings{:href => "#"}
              %i.icon-group
          .board-widgets-content
            .line-min-chart.min-chart
            .stat-text
              26458
              %i.up.icon-sort-up
              5%
    #forms.tab-pane
      %h4.side-head Forms
      %ul#nav.accordion-nav
        %li
          %a{:href => "form-elements.html"}
            %i.icon-list-alt
            Form Elements
            %span.notify-tip 50
        %li.active
          %a{:href => "form-components.html"}
            %i.icon-th
            Form Components
        %li
          %a{:href => "form-validation.html"}
            %i.icon-ok-circle
            Form Validation
            %span Quisque commodo lectus sit amet sem
        %li
          %a{:href => "form-wizard.html"}
            %i.icon-external-link
            Wizard
        %li
          %a{:href => "text-editor.html"}
            %i.icon-pencil
            WYSIWYG editor
            %span Quisque commodo lectus sit amet sem
    #features.tab-pane
      %h4.side-head Features
      %ul.accordion-nav
        %li
          %a{:href => "tables.html"}
            %i.icon-table
            Basic Tables
        %li
          %a{:href => "table-cloth.html"}
            %i.icon-table
            Tables-Theme
        %li
          %a{:href => "data-tables.html"}
            %i.icon-th
            Data Tables
        %li
          %a{:href => "grid.html"}
            %i.icon-columns
            Grid
        %li
          %a{:href => "typography.html"}
            %i.icon-font
            Typography
        %li
          %a{:href => "calendar.html"}
            %i.icon-calendar
            Calendar
        %li
          %a{:href => "file-manager.html"}
            %i.icon-folder-open
            File Manager
    #ui-elements.tab-pane
      %h4.side-head UI Elements
      %ul.accordion-nav
        %li
          %a{:href => "components-widgets.html"}
            %i.icon-list-alt
            UI Components
        %li
          %a{:href => "buttons-icons.html"}
            %i.icon-th-large
            Buttons & Icons
    #pages.tab-pane
      %h4.side-head Pages
      %ul.accordion-nav
        %li
          %img{:src => "images/imgOffClosed.png"}/
          %a{:href => "#"}
            %i.icon-minus-sign
            Error Pages
          %ul
            %li
              %a{:href => "page-403.html"}
                %i.icon-file-alt
                403 Error Page
            %li
              %a{:href => "page-404.html"}
                %i.icon-file-alt
                404 Error Page
            %li
              %a{:href => "page-405.html"}
                %i.icon-file-alt
                405 Error Page
            %li
              %a{:href => "page-500.html"}
                %i.icon-file-alt
                500 Error Page
            %li
              %a{:href => "page-503.html"}
                %i.icon-file-alt
                503 Error Page
        %li
          %a{:href => "login.html"}
            %i.icon-unlock
            Login Page
        %li
          %a{:href => "profile.html"}
            %i.icon-file
            Profile Page
        %li
          %a{:href => "search-page.html"}
            %i.icon-file
            Search Page
        %li
          %a{:href => "invoice.html"}
            %i.icon-file
            Invoice Page
        %li
          %a{:href => "gallery.html"}
            %i.icon-picture
            Gallery
        %li
          %a{:href => "pricing.html"}
            %i.icon-money
            Pricing Page
        %li
          %a{:href => "chat.html"}
            %i.icon-comments
            Chat Page
    #chart.tab-pane
      %h4.side-head Charts
      %ul.accordion-nav
        %li
          %a{:href => "flot-chart.html"}
            %i.icon-bar-chart
            Flot Charts
        %li
          %a{:href => "google-chart.html"}
            %i.icon-google-plus-sign
            Goolge
            %span Quisque commodo lectus sit amet sem

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
  
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "SuperCRM"
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    %link(href="http://fonts.googleapis.com/css?family=Dosis" rel="stylesheet" type="text/css")
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="favicon.ico" rel="shortcut icon")
  %body
    .layout
      .navbar.navbar-fixed-top
        .navbar-inner
          .container
            %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            %a.brand(href="#") SuperCRM
            .container.nav-collapse
              %ul.nav
                %li= link_to "Link 1", "/path1"
                %li= link_to "Link 2", "/path2"
                %li= link_to "Link 3", "/path3"
      .leftbar.leftbar-close.clearfix
        .admin-info.clearfix
          .admin-thumb
            %i.icon-user
          .admin-meta
            %ul
              %li.admin-username
                - if current_user
                  = current_user.username
                - else
                  Please Log in
              %li
                %a{:href => "#"} Edit Profile
              %li
                %a{:href => "#"} View Profile
                %a{:href => "#"}
                  %i.icon-lock
                  = link_to 'Logout', '/logout'
        = render :partial => 'layouts/left_side'
      .main-wrapper
        .row
          .span9
            = yield

            = link_to 'Log me out', '/logout' if current_user
          .span3
            .well.sidebar-nav
              %h3 Sidebar
              %ul.nav.nav-list
                %li.nav-header Sidebar
                %li= link_to "Link 1", "/path1"
                %li= link_to "Link 2", "/path2"
                %li= link_to "Link 3", "/path3"

        %footer
          %p &copy; SOS Wordpress 2013
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/user_sessions/new.html.haml
%h1 Login
= form_for @user_session, :url => user_session_path do |f|
  - if @user_session.errors.any?
    #error_explanation
      %h2
        = pluralize(@user_session.errors.count, "error")
        prohibited this team from being saved:
      %ul
        - @user_session.errors.full_messages.each do |msg|
          %li= msg  

.container
  = form_for @user_session, :url => user_session_path, :html => {:class => 'form-signin'} do |f|
    %h3.form-signin-heading Please sign in
    .controls.input-icon
      %i.icon-user-md
      = f.text_field :username, :placeholder => 'Username', :class => 'input-block-level'
    .controls.input-icon
      %i.icon-key
      = f.password_field :password, :placeholder => "Password", :class => 'input-block-level'
    %label.checkbox
      = f.check_box :remember_me
      Remember me
    = f.submit 'Sign in', :class => "btn btn-inverse btn-block"
    %h4 Forgot your password ?
    %p
      = link_to 'Click here to reset your password.', '#new_password_reset_path'
    %h5 Don't have an account yet ?
    = link_to new_account_url do
      = button_tag 'Create Account', :type => 'button',:class => 'btn btn-success btn-block' 

app/views/users/_form.haml
= form.label :username
%br/
= form.text_field :username
%br/
%br/


= #form.label :email
%br/
= #form.text_field :email
%br/
%br

= form.label :password, form.object.new_record? ? nil : "Change password"
%br/
= form.password_field :password
%br/
%br/
= form.label :password_confirmation
%br/
= form.password_field :password_confirmation
%br/

app/views/users/edit.html.haml
%h1 Edit My Account
= form_for @user, :url => account_path do |f|
  - if @user.errors.any?
    #error_explanation
      %h2
        = pluralize(@user.errors.count, "error")
        prohibited this team from being saved:
      %ul
        - @team.errors.full_messages.each do |msg|
          %li= msg  
 
  = render :partial => "form", :object => f
  = f.submit "Update"
%br/
= link_to "My Profile", account_path

app/views/users/new.html.haml
%h1 Register

%p
  Please Register to receive a regular newsletter containing items of photographic news, hint's, tips, inspiration and advanced notice of upcoming photographic workshops.
%p
  Registration is free and we will NOT pass on your details to anyone else.


%p Chris


= form_for @user, :url => account_path do |f|
  - if @user.errors.any?
    #error_explanation
      %h2
        = pluralize(@user.errors.count, "error")
        prohibited this team from being saved:
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
          
  = render :partial => "form", :object => f


  
  
  = f.submit "Register"

app/views/users/show.html.haml
%p
  %b Login:
  = h @user.username
%p
  %b Login count:
  = h @user.login_count
%p
  %b Last request at:
  = h @user.last_request_at
%p
  %b Last login at:
  = h @user.last_login_at
%p
  %b Current login at:
  = h @user.current_login_at
%p
  %b Last login ip:
  = h @user.last_login_ip
%p
  %b Current login ip:
  = h @user.current_login_ip
= link_to 'Edit', edit_account_path